# Generated by Django 3.2 on 2021-12-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_company_profile_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_team',
            name='uploads',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='uploads',
            field=models.ImageField(upload_to='media'),
        ),
    ]
