# Generated by Django 3.2 on 2021-12-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20211219_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_team',
            name='uploads',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
