# Generated by Django 3.2 on 2021-12-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_our_team_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='uploads',
            field=models.ImageField(upload_to='media'),
        ),
    ]
