# Generated by Django 3.2 on 2021-12-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_blog_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_team',
            name='uploads',
            field=models.ImageField(upload_to='static'),
        ),
    ]
