# Generated by Django 3.2 on 2021-12-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_our_team_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('country', models.CharField(blank=True, max_length=25)),
                ('pnumber', models.CharField(blank=True, max_length=12)),
                ('summary', models.TextField(blank=True, max_length=200)),
                ('jobtitle', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('workmode', models.CharField(blank=True, max_length=50)),
                ('workcountry', models.CharField(blank=True, max_length=25)),
                ('startdate', models.DateField(blank=True)),
                ('enddate', models.DateField(blank=True)),
                ('jobdesc', models.TextField(blank=True, max_length=150)),
                ('workhere', models.CharField(blank=True, max_length=10)),
                ('degree', models.CharField(blank=True, max_length=30)),
                ('institudename', models.CharField(blank=True, max_length=50)),
                ('graduationdate', models.DateField(blank=True)),
                ('edesc', models.TextField(blank=True, max_length=150)),
                ('skill1', models.CharField(blank=True, max_length=32)),
                ('skill2', models.CharField(blank=True, max_length=32)),
                ('skill3', models.CharField(blank=True, max_length=32)),
                ('skill4', models.CharField(blank=True, max_length=32)),
                ('skill5', models.CharField(blank=True, max_length=32)),
                ('skill6', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
