# Generated by Django 3.2 on 2021-12-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_team',
            name='uploads',
            field=models.ImageField(upload_to='internship/media'),
        ),
    ]
