# Generated by Django 3.2 on 2021-12-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_our_team_uploads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='verifyemail',
        ),
        migrations.DeleteModel(
            name='verifyotp',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.AlterField(
            model_name='our_team',
            name='uploads',
            field=models.ImageField(upload_to='media'),
        ),
    ]
